name: notako_app
description: A simple note taking app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  firebase_auth: ^4.4.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_svg:
  image_picker: 
  shared_preferences:
  figma_squircle:
  flutter_multi_select_items:
  firebase_database: ^10.1.2
  loading_indicator: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons:

flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/images/logo/png/notako_logo_only.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/logo/png/notako_logo_only.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/images/logo/png/notako_logo_only.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "lib/assets/images/logo/png/notako_logo_only.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/images/logo/png/notako_logo_only.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo/svg/
    - lib/assets/images/logo/png/
    - lib/assets/images/help/
    - lib/assets/images/
    - lib/assets/fonts/
  fonts:
    - family: DM-Sans
      fonts:
        - asset: lib/assets/fonts/dm_sans/dm_sans_regular.ttf
          weight: 400
        - asset: lib/assets/fonts/dm_sans/dm_sans_medium.ttf
          weight: 500
        - asset: lib/assets/fonts/dm_sans/dm_sans_bold.ttf
          weight: 600
    - family: Archivo
      fonts:
        - asset: lib/assets/fonts/archivo/archivo_light.ttf
          weight: 300
        - asset: lib/assets/fonts/archivo/archivo_regular.ttf
          weight: 400
        - asset: lib/assets/fonts/archivo/archivo_medium.ttf
          weight: 500
        - asset: lib/assets/fonts/archivo/archivo_bold.ttf
          weight: 600


