name: notako_app
description: A simple note taking app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  firebase_auth: ^4.4.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_svg:
  image_picker: 
  shared_preferences:
  figma_squircle:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19


flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/images/logo/png/notako_logo_with_text.png

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo/svg/
    - lib/assets/images/logo/png/
    - lib/assets/images/help/
    - lib/assets/fonts/
  fonts:
    - family: DM-Sans
      fonts:
        - asset: lib/assets/fonts/dm_sans/dm_sans_regular.ttf
          weight: 400
        - asset: lib/assets/fonts/dm_sans/dm_sans_medium.ttf
          weight: 500
        - asset: lib/assets/fonts/dm_sans/dm_sans_bold.ttf
          weight: 600
    - family: Archivo
      fonts:
        - asset: lib/assets/fonts/archivo/archivo_light.ttf
          weight: 300
        - asset: lib/assets/fonts/archivo/archivo_regular.ttf
          weight: 400
        - asset: lib/assets/fonts/archivo/archivo_medium.ttf
          weight: 500
        - asset: lib/assets/fonts/archivo/archivo_bold.ttf
          weight: 600


